version: '2'

services: 
  httpd_php:
    build: ./php-httpd
    image: httpd-php:1.0
    container_name: httpd-php
    depends_on:
     - db
     - cache_redis
    links:
     - db
     - cache_redis
    ports:
     - "1080:80"
    volumes:
      - ./src:/var/www:rw
      - ./image:/var/www/image:rw
    environment:
      VIRTUAL_HOST: web.local
  db:
    build: ./mysql-server
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "33006:3306"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
  cache_redis:
    build: ./cache-redis
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "63799:6379"
  nginx_static:
    build: ./nginx-server
    image: nginx:alpine
    container_name: nginx_file_server
    ports:
      - "8080:8080"
    volumes:
      - ./image:/var/www/image:rw
      
       
