version: '2'

services: 
  httpd_php:
    build: ./php-httpd
    image: httpd-php:1.0
    container_name: httpd-php
    depends_on:
     - db
    links:
     - db
    ports:
     - "1080:80"
    volumes:
      - ./pro:/var/www/html:rw
    environment:
      VIRTUAL_HOST: web.local
  db:
    build: ./mysql
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "33006:3306"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
       
